name: CI
"on":
  push: null
jobs:
  CheckHost:
    runs-on: ubuntu-latest
    steps:
    - run: cat /etc/os-release
    - run: |
        whoami
        id -u
        id -g
    - run: docker --version
